#pragma once
#include "LiteMath.h"
using LiteMath::float3, LiteMath::float4, LiteMath::float3x3, LiteMath::double3, LiteMath::double4, LiteMath::double3x3;

/*
    Quaternion convention here:
        q = q_r + i * q_x + j * q_y + k * q_z
    is represented as
        float4(q_x, q_y, q_z, q_r)
*/

inline float4 quaternion_from_rotation_matrix(float3x3 m)
{
    /*
          Generated by LLM
          I dont know what is happening...
    */
    float m00 = m[0][0], m01 = m[0][1], m02 = m[0][2];
    float m10 = m[1][0], m11 = m[1][1], m12 = m[1][2];
    float m20 = m[2][0], m21 = m[2][1], m22 = m[2][2];

    float trace = m00 + m11 + m22;
    float4 q = {0, 0, 0, 0};

    if (trace > 0.0f)
    {
        float s = 0.5f / std::sqrt(trace + 1.0f);
        q.w = 0.25f / s;
        q.x = (m21 - m12) * s;
        q.y = (m02 - m20) * s;
        q.z = (m10 - m01) * s;
    }
    else if (m00 > m11 && m00 > m22)
    {
        float s = 2.0f * std::sqrt(1.0f + m00 - m11 - m22);
        q.w = (m21 - m12) / s;
        q.x = 0.25f * s;
        q.y = (m01 + m10) / s;
        q.z = (m02 + m20) / s;
    }
    else if (m11 > m22)
    {
        float s = 2.0f * std::sqrt(1.0f + m11 - m00 - m22);
        q.w = (m02 - m20) / s;
        q.x = (m01 + m10) / s;
        q.y = 0.25f * s;
        q.z = (m12 + m21) / s;
    }
    else
    {
        float s = 2.0f * sqrt(1.0f + m22 - m00 - m11);
        q.w = (m10 - m01) / s;
        q.x = (m02 + m20) / s;
        q.y = (m12 + m21) / s;
        q.z = 0.25f * s;
    }

    return normalize(q);
}

inline float4 quaternion_product(float4 a, float4 b)
{
    float3 a1 = to_float3(a);
    float3 b1 = to_float3(b);
    return to_float4(a.w * b1 + b.w * a1 + cross(a1, b1), a.w * b.w - dot(a1, b1));
}

inline float4 quaternion_conjugate(float4 q)
{
    // return to_float4(-to_float3(q), q.w);
    return float4{-q.x, -q.y, -q.z, q.w};
}

inline float3 quaternion_rotate_vector(float4 q, float3 v)
{
    return to_float3(quaternion_product(q, quaternion_product(to_float4(v, 0), quaternion_conjugate(q))));
}

inline double4 quaternion_from_rotation_matrix(double3x3 m)
{
    /*
        Generated by LLM
        I dont know what is happening...
    */
    double m00 = m[0][0], m01 = m[0][1], m02 = m[0][2];
    double m10 = m[1][0], m11 = m[1][1], m12 = m[1][2];
    double m20 = m[2][0], m21 = m[2][1], m22 = m[2][2];

    double trace = m00 + m11 + m22;
    double4 q = {0, 0, 0, 0};

    if (trace > 0.0)
    {
        double s = 0.5 / std::sqrt(trace + 1.0);
        q.w = 0.25 / s;
        q.x = (m21 - m12) * s;
        q.y = (m02 - m20) * s;
        q.z = (m10 - m01) * s;
    }
    else if (m00 > m11 && m00 > m22)
    {
        double s = 2.0 * std::sqrt(1.0 + m00 - m11 - m22);
        q.w = (m21 - m12) / s;
        q.x = 0.25f * s;
        q.y = (m01 + m10) / s;
        q.z = (m02 + m20) / s;
    }
    else if (m11 > m22)
    {
        double s = 2.0 * std::sqrt(1.0 + m11 - m00 - m22);
        q.w = (m02 - m20) / s;
        q.x = (m01 + m10) / s;
        q.y = 0.25 * s;
        q.z = (m12 + m21) / s;
    }
    else
    {
        double s = 2.0 * std::sqrt(1.0 + m22 - m00 - m11);
        q.w = (m10 - m01) / s;
        q.x = (m02 + m20) / s;
        q.y = (m12 + m21) / s;
        q.z = 0.25 * s;
    }

    return normalize(q);
}

inline double4 quaternion_product(double4 a, double4 b)
{
    double3 a1 = to_double3(a);
    double3 b1 = to_double3(b);
    return to_double4(a.w * b1 + b.w * a1 + cross(a1, b1), a.w * b.w - dot(a1, b1));
}

inline double4 quaternion_conjugate(double4 q)
{
    // return to_float4(-to_float3(q), q.w);
    return double4{-q.x, -q.y, -q.z, q.w};
}

inline double3 quaternion_rotate_vector(double4 q, double3 v)
{
    return to_double3(quaternion_product(q, quaternion_product(to_double4(v, 0), quaternion_conjugate(q))));
}
