
set(CLIPPER2_UTILS OFF)
set(CLIPPER2_TESTS OFF)
set(CLIPPER2_EXAMPLES OFF)

set(MESSAGE_LOG_LEVEL ${CMAKE_MESSAGE_LOG_LEVEL})
set(CMAKE_MESSAGE_LOG_LEVEL ERROR)
litert_import(clipper2/CPP EXCLUDE_FROM_ALL SYSTEM)
set(CMAKE_MESSAGE_LOG_LEVEL ${MESSAGE_LOG_LEVEL})

# Removing -lm flag on Windows because libm does not exist
if(WIN32)
    get_property(CLIPPER2_LINK_LIBRARIES TARGET Clipper2 PROPERTY LINK_LIBRARIES)
    list(REMOVE_ITEM CLIPPER2_LINK_LIBRARIES -lm)
    set_property(TARGET Clipper2 PROPERTY LINK_LIBRARIES ${CLIPPER2_LINK_LIBRARIES})

    get_property(CLIPPER2_LINK_LIBRARIES TARGET Clipper2 PROPERTY INTERFACE_LINK_LIBRARIES)
    list(REMOVE_ITEM CLIPPER2_LINK_LIBRARIES -lm)
    set_property(TARGET Clipper2 PROPERTY INTERFACE_LINK_LIBRARIES ${CLIPPER2_LINK_LIBRARIES})
endif()
